### ISSUE TITLE
Překročen limit při načítání galerie

### ISSUE THREAD

**Issue by jakubpetrak** [skaut/skaut-google-drive-gallery#246]
Poslední dobou prakticky není možné galerii využívat, jelikož z 90% dojde k hlášce o překročení limitu a je konec načítání galerie...

https://fotky.prosek.org/problem-s-galerii/

Nějaké tipy jak se tomu vyhnout? Načítání počtu složek je vypnuté, limity pro api na maximum (pokud jsem se tedy dobře díval), ...

**Comment by adamjanovsky** [comment]
I'm certain that this needs to be resolved on the code level (and I'm certain that there is huge space for improvement), but in the meantime you can try the fix I used: https://github.com/skaut/skaut-google-drive-gallery/issues/231 (basically asking Google Support for higher quota, 10k/user/100sec suffices in my case).

**Comment by marekdedic** [comment]
I'm not sure about improvement at the code level (open to ideas though). It seems to me that Google is blocking *some* requests for *some* users even when you're below the quota. Maybe new users? Maybe based on previous demand? I have no idea...

Anyway, if the problems persist, try splitting the gallery into folders by years/etc... Having less folders at once should help.

**Comment by CmeldaVales** [comment]
hele u mě na webech se chyba limitu zobrazuje docela pravidelně.
z vlákna #231 a tomto jsem pochopil že je to ten problém zejména pravidla _**Queries per 100 seconds per user**_ které mám od googlu nastavenou na 1000.
Procesem zvýšení sem zatím neprošel. Jde tyto limity ladit jinak než jednotlivými žádostmi na google?
@marekdedic či @kalich5 nemají kontakt že by se o to žádalo nějak hromadně? Ano máme tady plugin, dělá všem tyto chyby.

**Comment by Woromi** [comment]
Trošku mi není jasné, jak tedy můžu požádat Google o zvýšení limitu. Nenašel jsem jinou možnost, jak o to požádat, než tohle: [https://console.developers.google.com/iam-admin/quotas](https://console.developers.google.com/iam-admin/quotas). Chce to po mě ale billing account. Jde to nějak i bez něj? A pokud ne, z vlákna #231 jsem pochopil, že i když připojím billing account a požádám o zvýšení, nic platit nebudu. Je to tak?

PS: Měl bych tady taky psát anglicky?

**Comment by adamjanovsky** [comment]
Hi, you're looking at the correct link. You should be seeing the phrase "apply for higher quota" somewhere. 
I indeed needed to create the billing account (you still have to authorize any transaction and you don't need to pay anything, so you should be safe) and forgot all about that. Now, I canceled that account and the higher quotas still hold :). 

Thus, the recipe could be: 1) create billing account, 2) increase quotas, 3) delete billing account.

However, the quotas are increased by actual people. And that people see that you exhibit zero error rate, hence they will not be willing to increase them for you. Make sure you explain the situation well for them. It took 5 mails and 10 days in my case ^^.

Ad English, since this plugin shall be used by anyone on the Earth, writing down this experience in Czech discriminates potential readers.

**Comment by marekdedic** [comment]
Hi,
it's a bit strange with the billing account... But what @adamjanovsky suggests is smart.

Ad language: I try to keep it here in English because there have been some non-czech speaking people contributing to the plugin and asking questions (And when I wanted to point them to older issues, I realized they were in Czech...). But both is fine by me.

**Comment by kalich5** [comment]
https://github.com/skaut/skaut-google-drive-gallery/issues/494

**Comment by kalich5** [comment]
We will try to integrate automatic recovery #494

**Comment by marekdedic** [comment]
Hi guys, closing this as it was solved in version 2.10 :tada:

**Comment by adamjanovsky** [comment]
That's a great news! What was the solution in the end?

**Comment by marekdedic** [comment]
Rework the entire way the plugin accesses Google Drive to go through a centralized request-creating-and-automatic-batching function and then retry on failure with exponential backoff. See #673 and #748.
